### ISSUE TITLE
Existe un error en las rutas autenticadas.

### ISSUE THREAD

**Issue by evilelliot** [ninoxit/eventee#3]
Hasta el momento no he logrado hacer que el contexto que abarca la innerApp esté presente en las rutas, por lo que me es imposible programar un comportamiento del tipo 'if else' para el caso de estar autenticado o no.

De lejos mi solución ha sido crear un componente extra para cargarlo en caso de que esté autenticado y que el usuario de click ahí para que se vaya a la página de perfil, pero eso no es práctico y queda horrendo.

```typescript
import { createFileRoute, redirect } from '@tanstack/react-router';
import LoginLayout from '../../components/login/LoginLayout';
import { useAuth } from '../../context/AuthProvider';
import AuthComponent from '../../components/auth/AuthComponent';

export const Route = createFileRoute('/login/')({
  component: () => {
    const { auth } = useAuth(); 
    if (auth) {
      console.log("Hello I'm falling here");
      return <AuthComponent origin="login" />
    }else{
      return <LoginLayout />;
    }
  }
});

```

**Comment by ninoxander** [comment]
# Closed!
Cerramos ya este issue, nada más cambiamos de versión a la 1.19.4 del router de tanstack y listo.
Nada más añadimos un commit para el fix y listo.
